### ISSUE TITLE
Light Sensor does not record 0 lux readings

### ISSUE THREAD

**Issue by rabidfurball** [sosprz/nettemp#10]
I am using nettemp to monitor light levels in a room with a regular cycle between complete darkness and moderate light levels.  I use v 8.4.64 master on a raspberry pi B+ with an Adafruit TSL2561 Digital Luminosity/Lux/Light Sensor.  

Nettemp logs positive light values perfectly, however, for the period that the sensor registers 0.0 lux, it does not seem to log any 0.0 values into the highcharts (but it does rarely log near zero numbers like 0.2).  Is there a way to make it log the 0.0 values, which would result in a graph similar to the red line in the attached image?

![image](https://cloud.githubusercontent.com/assets/1872997/6531366/6c0fa630-c3fe-11e4-8a6c-cf5b1fd5695d.png)

**Comment by rabidfurball** [comment]
It would also be really cool if this sensor could report infrared separate from full spectrum, which I know it is capable of...

**Comment by rabidfurball** [comment]
Still a problem...

![image](https://cloud.githubusercontent.com/assets/1872997/7073821/ac80c064-debb-11e4-9a53-8cfec4bbeadd.png)

**Comment by sosprz** [comment]
Hi in beta version lux write 0 value.
