### ISSUE TITLE
Possibility to "adjust" sensor readings

### ISSUE THREAD

**Issue by sq6emm** [sosprz/nettemp#12]
Could you please add a feature that will allow user to adjust sensor readings?
I am using nettemp for monitoring of some temperature critical machine.
However DS18B20 have sometimes even up to 0,5 degree difference between calibrated temperature sensor.

I think such feature to add or subtract defined value to sensor reading would be great.

**Comment by sosprz** [comment]
Hi, this function is in latest version but not work on charts.
