### ISSUE TITLE
1wire_gpio_i2c_read.php doesn't properly convert C -> F

### ISSUE THREAD

**Issue by rmbolger** [sosprz/nettemp#26]
In d67f2200e0dc6afdf49e6f95dc581e7510bc7232, `modules/sensors/read` was changed such that `modules/sensors/1wire/1wire_gpio_i2c_read` was replaced with `modules/sensors/1wire/1wire_gpio_i2c_read.php`. But the PHP version doesn't respect the C/F `temp_scale` setting and always inserts Celsius values.

I believe this is because the PHP version [includes the contents](https://github.com/sosprz/nettemp/blob/beta/modules/sensors/1wire/1wire_gpio_i2c_read.php#L23) of `receiver.php` to use the `db` function. But the C -> F check/conversion is normally done outside of that function in the [main page loop](https://github.com/sosprz/nettemp/blob/beta/receiver.php#L227).

The C -> F conversion should either be moved inside the `db` function or added to `1wire_gpio_i2c_read.php`.

**Comment by sosprz** [comment]
Hi, You have right i forgot about this conversion. For now changed code to: https://github.com/sosprz/nettemp/blob/beta/receiver.php#L61
