### ISSUE TITLE
Problem z funkcjami gpio.

### ISSUE THREAD

**Issue by swiezaks** [sosprz/nettemp#47]
1. Po dodaniu przekaźnika w funkcji simple on/off na głównej stronie w grupie gpio można włączyć gpio ale kolejne przyciśnięcie nic nie daje. przycisk pomimo zmiany stanu na przeciwny nie wyłącza gpio. dopiero w device można go wyłączyć
2. Nie działa funkcja time- ustawienie czasu np. 1 min -powoduje załączenie przekaźnika ale go nie wyłącza.

**Comment by sosprz** [comment]
Hej, podeślij screen z swojej list gpio ze statusu. U mnie działają ok :)

**Comment by swiezaks** [comment]
Przepraszam, że tak późno odpisuję ale musiałem postawić system na nowej karcie ponieważ stary miał ponad rok i myślałem, że to objaw padającej karty pamięci ale na nowym systemie identyczny objaw.
Może po kolei
Raspberry pi B+, raspbian stretch z najnowszymi aktualizacjami, NT beta 4.1.26. system całkiem czysty, tylko dodane czujniki na usb ds9097 oraz jeden przekaźnik na gpio 25.
Problem nr.1
Przekaźnik mam ustawiony simple ON/OFF. i jest włączony
![image](https://user-images.githubusercontent.com/31879697/33968010-306ae464-e066-11e7-8e65-31467f13f48d.png)
jednak na głównej w status mam na off i naciśnięcie suwaka powoduje chwilową zmianę na ON i znowu jest OFF- wentylator cały czas działa czyli jest na ON
![image](https://user-images.githubusercontent.com/31879697/33967949-eb2c9582-e065-11e7-9936-cb98de5ced35.png)
Problem nr.2
Włączenie na 1 min.
![image](https://user-images.githubusercontent.com/31879697/33968129-d0c42010-e066-11e7-9a06-ac772d21b583.png)
i status
![image](https://user-images.githubusercontent.com/31879697/33968154-e9f4ac9e-e066-11e7-9807-8d0ecb006007.png)
Mija 5min a wentylator nadal działa.
Pozdrawiam
