### ISSUE TITLE
The server encountered an internal error

### ISSUE THREAD

**Issue by rasmatic** [sosprz/nettemp#56]
Świerza instalacja na raspberry pi:

pi@raspberrypi:~ $ curl -k -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":"czujnik","password":"Czujnik1"}' https://192.168.77.88/register
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
pi@raspberrypi:~ $

pi@raspberrypi:~ $ python3 jwt_test.py
[*] Register and send {'username': 'czujnik', 'password': 'Czujnik1'}
Traceback (most recent call last):
  File "jwt_test.py", line 11, in <module>
    token=r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

???
Pozdrawiam

**Comment by uzi18** [comment]
proponuje zglosic tutaj: https://github.com/mariano78/nettemp to aktualnie rozwijany fork majacy sporo poprawek
@mariano78

**Comment by sosprz** [comment]
> proponuje zglosic tutaj: https://github.com/mariano78/nettemp to aktualnie rozwijany fork majacy sporo poprawek
> @mariano78

Moja aktualna wersja jest na pythonie a moja stara z której forkujecie to nie rozwijany php.

**Comment by sosprz** [comment]
> Świerza instalacja na raspberry pi:
> 
> pi@raspberrypi:~ $ curl -k -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":"czujnik","password":"Czujnik1"}' https://192.168.77.88/register
> 
> <title>500 Internal Server Error</title>
> # Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> 
> pi@raspberrypi:~ $
> pi@raspberrypi:~ $ python3 jwt_test.py
> [*] Register and send {'username': 'czujnik', 'password': 'Czujnik1'}
> Traceback (most recent call last):
> File "jwt_test.py", line 11, in
> token=r.json()
> File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
> return complexjson.loads(self.text, **kwargs)
> File "/usr/lib/python3.7/json/**init**.py", line 348, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> ???
> Pozdrawiam

Hej, czy masz stworzonego uzytkownika w systemie? Dopiero wtedy można się rejestrować.

**Comment by sosprz** [comment]
> > Świerza instalacja na raspberry pi:
> > pi@raspberrypi:~ $ curl -k -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":"czujnik","password":"Czujnik1"}' https://192.168.77.88/register
> > <title>500 Internal Server Error</title>
> > # Internal Server Error
> > The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> > pi@raspberrypi:~ $
> > pi@raspberrypi:~ $ python3 jwt_test.py
> > [*] Register and send {'username': 'czujnik', 'password': 'Czujnik1'}
> > Traceback (most recent call last):
> > File "jwt_test.py", line 11, in
> > token=r.json()
> > File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
> > return complexjson.loads(self.text, **kwargs)
> > File "/usr/lib/python3.7/json/**init**.py", line 348, in loads
> > return _default_decoder.decode(s)
> > File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
> > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
> > raise JSONDecodeError("Expecting value", s, err.value) from None
> > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > ???
> > Pozdrawiam
> 
> Hej, czy masz stworzonego uzytkownika w systemie? Dopiero wtedy można się rejestrować.

Hej, poprawiłem w najnowszej wersji rzeczywiście był problem.
